### ISSUE TITLE
Bootstrap .label-TYPE not loaded

### ISSUE THREAD

**Issue by nblake989** [creativetimofficial/light-bootstrap-dashboard-pro#11]
Experienced issues with the _labels.scss partial not loading properly in my app and in the example pages. Seems that the `.label` and `.label-danger` colored classes are not updating to the LBDP color variables.

Seen here in the documentation example:
![screen shot 2016-09-15 at 1 03 49 pm](https://cloud.githubusercontent.com/assets/8633545/18565527/ecd96860-7b44-11e6-8b9a-c58622c11836.png)

**Comment by alexandru-paduraru** [comment]
Hi Nick! Thank you for pointing out. We've checked and it looks like there are no variables at all in the labels file 😱 😱 😱 

<img width="359" alt="screen shot 2016-09-16 at 17 12 52" src="https://cloud.githubusercontent.com/assets/2517758/18588867/eabeb8fe-7c30-11e6-9ccf-f5b4f6e4bc71.png">

We wrote this and we will add them in the next update release. If you want a quick fix please add this variables 
``` 
$color-azure      // for .label-info
$color-red          // for .label-danger
$color-green      // for .label-success
$color-orange   // for .label-warning
$color-blue       // for .label-primary
``` 

and compile again the SCSS with [Koala App](http://koala-app.com/)

Please let us know if we can help with anything else.

Best,
Alex
