### ISSUE TITLE
Windows scrolling problems

### ISSUE THREAD

**Issue by nolanng** [creativetimofficial/light-bootstrap-dashboard-pro#17]
Hi there, we have problems with the scroll in windows, attached files

[dashboardtemplate.txt](https://github.com/timcreative/light-bootstrap-dashboard-pro/files/643507/dashboardtemplate.txt)

[dashboard.txt](https://github.com/timcreative/light-bootstrap-dashboard-pro/files/643508/dashboard.txt)

Can they tell us where to put some code?

![consulta](https://cloud.githubusercontent.com/assets/24486227/21070379/9670fbda-be49-11e6-8374-6ddbd250f892.png)

Regards !

**Comment by alexandru-paduraru** [comment]
@nolanng thank you for using our product. Can you please send us the credentials to login to your dashboard then we will check what can be the issues and give you a solution?

Best,
Alex

**Comment by nolanng** [comment]
https://cp58.webempresa.eu:2083/

usuario:  coopetransaccion

clave: Coope#tran2016

Regards !   public html/dashboard.php

**Comment by alexandru-paduraru** [comment]
@nolanng thank you for the credentials. I need the credentials to view the Dashboard, not the cpanel. I've also edited your comment so nobody can see your credentials. Please give us the link and the account credentials so we can login from windows and check the problem.

Best,
Alex

**Comment by swebal** [comment]
Did you solve this? I can't scroll down on windows IE or Chrome when the menu is expanded, but scrolling works fine when the menu is minimized (fixed scrolling).

What CSS (and where) should I add to make the scrolling fixed for windows all the time?

**Comment by alexandru-paduraru** [comment]
@swebal please make sure the scrollbar library is called right, at this moment for windows, it is called in `assets/js/light-bootstrap-dashboard.js` line 48 like this:

```(function(){
    isWindows = navigator.platform.indexOf('Win') > -1 ? true : false;

    if (isWindows && !$('body').hasClass('sidebar-mini')){
       // if we are on windows OS we activate the perfectScrollbar function
       $('.sidebar .sidebar-wrapper, .main-panel').perfectScrollbar();

       $('html').addClass('perfect-scrollbar-on');
   } else {
       $('html').addClass('perfect-scrollbar-off');
   }
})();
```
Then all the CSS for the perfect-scrollbar-on/off is in `assets/css/light-bootstrap-dashboard.css` starting with line 4561. If you want to remove the scrollbar for windows you can remove this code from the CSS:

```css
.perfect-scrollbar-on .sidebar .sidebar-wrapper, .sidebar .sidebar-wrapper, .perfect-scrollbar-on
.main-panel,
.main-panel {
  overflow: hidden;
}
```

Please let us know if that was working fine.

Best,
Alex

**Comment by swebal** [comment]
I changed it to overflow: auto; and now it works.
