### ISSUE TITLE
boxed version

### ISSUE THREAD

**Issue by manuschiller** [creativetimofficial/light-bootstrap-dashboard-pro#18]
Hi! 

In the screenshots on your website I can see a boxed version of your dashboard which looks really neat!

However, in the demo I can not switch to the boxed version.
Is there a boxed version configuration available in the pro version?

regards

**Comment by alexandru-paduraru** [comment]
@manuschiller thank you for your interest in our product. The Boxed version doesn't exist, it is in the screenshot just to show that there are different pages in the same Dashboard so we had to do something to make it support 3 images in the same screenshot (Photoshop). I will talk with my team and we can create a boxed version in the next update. If this is something really urgent for you, we can figure out something that looks nice.

All the best,
Alex
