### ISSUE TITLE
Tooltips with Datatables.net

### ISSUE THREAD

**Issue by waroo** [creativetimofficial/light-bootstrap-dashboard-pro#26]
I am trying to add tooltips to the column headers of a datatables.net table however when I hover over the column header to display the tooltip, a blank column header is inserted to the right of the tooltip column and all other headers are shifted over to the right one.

As an example I modified the tables/bootstrap-table.html file as:
```
<th rel="tooltip" title="Name" >Name</th>
<th rel="tooltip" title="Position" >Position</th>
<th rel="tooltip" title="Office" >Office</th>
<th rel="tooltip" title="Age" >Age</th>
<th rel="tooltip" title="Start date" >Start date</th>

....

<script>
$(document).ready(function() {
    $('[rel="tooltip"]').tooltip();
});
</script>
```

Here is a screenshot.
![image](https://user-images.githubusercontent.com/890931/28179277-73832da2-67cf-11e7-949a-e5418698881d.png)

**Comment by dragosct10** [comment]
Hi @waroo! Sorry for the late response. For fixing the issue that you have with tooltips please add on every `<th rel="tooltip" title="Something" >Something</th>` the attribute `data-container="body"`, so in the final your code must be like this: `<th rel="tooltip" title="Something" data-container="body" >Something</th>`. Please let us know if everything is working fine! 

Regards,
Dragos
