### ISSUE TITLE
Problem with sidebar when the page content is very little

### ISSUE THREAD

**Issue by erhanalankus** [creativetimofficial/light-bootstrap-dashboard-pro#27]
Our project requires a lot of buttons on the sidebar. When there is little content in the "content" div, the part of the sidebar that's after the end of "footer" does not look right, when the sidebar is in narrow mode.

We like how the sidebar behaves when it is expanded horizontally. It takes all the height and scrolls inside if necessary and it does not scroll with the center part of the page. However, when the sidebar is in narrow mode, it behaves differently. It scrolls with the center part of the page and we don't like it.

We tried to make the narrow sidebar behave like the wide sidebar but we were unable to do so without causing different visual errors.

So we thought maybe this is an issue. If it's not, I'd appreciate it if you can point me to relevant documentation about this task.

edit: We are currently using "Light Bootstrap Dashboard PRO - V1.3.0"

**Comment by alexandru-paduraru** [comment]
@erhanalankus thank you for using our product, just commented to let you know that we are working on a solution for you to have the menu act in the same way when it is minified, something like we have here: http://md-pro-angular2.creative-tim.com/

We will come back with a solution in 1-2 days.

Best,
Alex

**Comment by dragosct10** [comment]
Hi @erhanalankus! Sorry for the late response. Please follow the next steps to fix the issues:

1.  Take the uploaded javascript file `light-bootstrap-dashboard.js` and replace in `assets/js/light-bootstrap-dashboard.js` with the new one.
[light-bootstrap-dashboard.js.zip](https://github.com/creativetimofficial/light-bootstrap-dashboard-pro/files/1190211/light-bootstrap-dashboard.js.zip)

2. Take the uploaded scss partial `_misc.scss` and replace in `assets/sass/lbd/_misc.scss` with the new one.
[_misc.scss.zip](https://github.com/creativetimofficial/light-bootstrap-dashboard-pro/files/1190209/_misc.scss.zip)

3. Take the uploaded scss partial `_sidebar-and-main-panel.scss` and replace in `assets/sass/lbd/_sidebar-and-main-panel.scss` with the new one.
[_sidebar-and-main-panel.scss.zip](https://github.com/creativetimofficial/light-bootstrap-dashboard-pro/files/1190220/_sidebar-and-main-panel.scss.zip)

4. Now you have to put in all the html pages the new structure for the sidebar. I will attach you the the  `dashboard.html` page and then you must open this page and search for the div with class `.sidebar` and after that take the entire div with class `.sidebar` and put in all the html pages to have the same structure. 
[dashboard.html.zip](https://github.com/creativetimofficial/light-bootstrap-dashboard-pro/files/1190236/dashboard.html.zip)

5. Now you have to compile your scss with [Koala](koala-app.com) and please be sure that your output path is `assets/css/light-bootstrap-dashboard.css`.

Regards,
Dragos
