### ISSUE TITLE
Collapsing Datatable. Actions doesn't work

### ISSUE THREAD

**Issue by lxlarcadelxl** [creativetimofficial/light-bootstrap-dashboard-pro#28]
Hello,

if i have a wide table and i resize the browser the last columns collapse with the actions for example.
After the + appears in the first column i can open the actions.
But the functions on the actions doesn't work.
In the example datatables Page it does not work either.

![datatablecollapseactionsdoesntwork](https://user-images.githubusercontent.com/23142574/30202902-5e026910-9480-11e7-91b6-7b516d6427dc.PNG)

I hope you can fix it becauise i'm stuck with my reports on your template :(

Best regards
Marcus

**Comment by alexandru-paduraru** [comment]
@lxlarcadelxl thank you for using our product. We've checked and you are right, there is an issue when the table it's changing it's structure for mobile.

Please go to the code where you initialize the table and replace this code:

```js
    table.on( 'click', '.edit', function () {
	$tr = $(this).closest('tr');

   var data = table.row($tr).data();
       alert( 'You press on Row: ' + data[0] + ' ' + data[1] + ' ' + data[2] + '\'s row.' );
   } );
```
with this one:

```js
table.on( 'click', '.edit', function () {
    $tr = $(this).closest('tr');		
    
    if($tr.hasClass('child')){
        $tr = $tr.prev('.parent');
    }
			
    var data = table.row($tr).data();
        alert( 'You press on Row: ' + data[0] + ' ' + data[1] + ' ' + data[2] + '\'s row.' );
    } );
```

This is the example for edit, you can add that to remove, like and other functions too. It will work fine.

Let us know how it was working.

Best,
Alex

**Comment by lxlarcadelxl** [comment]
Hey Alex,

thanks for your quick answer. 
It works fine on the example table. So it is fixed actually. But my case is a bit diffrent because i use a jquery and swal.

I use my script like this in the footer part:

`  $('button.delete-paket').click(function() {
    var paketId = $(this).attr("data-paket-id");
    deletepaket(paketId);
  });

  function deletepaket(paketId) {
    swal({
      title: "Sind Sie sicher ?", 
      text: "Der Vorgang kann nicht rückgängig gemacht werden", 
      type: "warning",
      showCancelButton: true,
      closeOnConfirm: false,
      cancelButtonText: "Abbrechen",
      confirmButtonText: "Ja, löschen!",
      confirmButtonColor: "#ec6c62"
    }, function() {
      $.ajax({
        url: "includes/delete.php?id=" + paketId,
        type: "DELETE"
      })
      .done(function(data) {

        swal("Gelöscht!", "Datensatz wurde erfolgreich gelöscht!", "success");
        window.setTimeout(function(){location.reload()},2000)
        // location.reload();

      })

      .error(function(data) {

        swal("Oops", "Datei nicht gefunden!", "error");
      });

    });
  }`



My markup is:

`<button rel="tooltip" data-original-title="Löschen" class="delete-paket btn btn-simple btn-icon btn-danger" data-paket-id="<?php echo $hsepaket->id;?>"><i class="fa fa-times"></i></button>`


So how could i integrate my function into your workflow.
Or make my function work like it helped on yours.

I would be very happy for any help.

Best wishes,
Marcus

**Comment by lxlarcadelxl** [comment]
no one has an idea ?

**Comment by alexandru-paduraru** [comment]
@lxlarcadelxl can you please send us a demo link? I couldn't really understand what is happening there and how the table is related to the button.

Best,
Alex
