### ISSUE TITLE
How to make the sidebar-mini Sticky  ?

### ISSUE THREAD

**Issue by lxlarcadelxl** [creativetimofficial/light-bootstrap-dashboard-pro#30]
i use the mini sidebar on the body tag

<body class="sidebar-mini">

if the full menu is out it keeps sticky. if i use the sidebar-mini option it is not sticky.
Is there a class to make it sticky or something ?

Best 
Marcus

**Comment by alexandru-paduraru** [comment]
@lxlarcadelxl the sidebar mini will be sticky after you follow the tutorial from this issue: #29. Please let's keep the issue in only 1 place so we don't miss anything important. @dragosct10 will help you there with the problem if you let us know on which step you've got stuck.

Best,
Alex
