### ISSUE TITLE
Shift mobile sidebar to left hand side

### ISSUE THREAD

**Issue by nzjrs** [creativetimofficial/light-bootstrap-dashboard-pro#34]
A right-hand sidebar is against google material design (or more relevant, against what users currently expect because everyone follows google's lead here).

Can I move the sidebar to the left on mobile?

**Comment by alexandru-paduraru** [comment]
@nzjrs thank you for using our product. Please check this example: https://github.com/creativetimofficial/light-bootstrap-dashboard-pro/issues/20

Best,
Alex
