### ISSUE TITLE
Missing .angular-cli.json

### ISSUE THREAD

**Issue by AzriZzz** [creativetimofficial/light-bootstrap-dashboard-pro#37]
Hello, I facing a problem with the template, it's missing file .angular-cli.json. Because of this, I can't integrate with TinyMCE WYSIWIG. I'm using template lbd-pro-angular2-html-v1.0.1 2.

**Comment by alexandru-paduraru** [comment]
@AzriZzz thank you for using our product. This is the repo for the HTML version, not the Angular, here is the one for Angular: https://github.com/creativetimofficial/light-bootstrap-dashboard-pro-angular.

Please download again our latest v1.2.1 from www.creative-tim.com and you will have there the `angular-cli.json`

Best,
Alex
