### ISSUE TITLE
The slide bar is broken on IE

### ISSUE THREAD

**Issue by nguyenlnc** [creativetimofficial/light-bootstrap-dashboard-pro#39]
Hi creativetimers,

I access the link http://demos.creative-tim.com/light-bootstrap-dashboard-pro/examples/dashboard.html via IE11. The slide bar is broken. Please help me check.

![image](https://user-images.githubusercontent.com/24447765/33982989-1b186530-e0e5-11e7-8b65-9c2230b60ea4.png)

Thank you

**Comment by groovemen** [comment]
Hi nguyenlnc ! 

Thank you for your observation. Here are the steps to solve that issue:

1. Please erase the `justify-content-end` class from `navbar-collapse` div
2. Then erase the `mr-auto` class from `navbar-collapse` first child (ul) and set the `ml-auto` to the second `ul` that contains the dropdowns.
3. Also, set a margin-right to `.navbar-wrapper .navbar-brand`

We'll fix this issue for the next update.

Greetings,
Stefan

**Comment by nguyenlnc** [comment]
Hi groovemen,

Thank you for your feedback. But It seems like previous or maybe I missed something.

![1](https://user-images.githubusercontent.com/24447765/34239067-95447f22-e637-11e7-9aeb-5e56206682ab.JPG)

This is code

![2](https://user-images.githubusercontent.com/24447765/34239078-a5cb9fce-e637-11e7-8082-3e771e458273.JPG)

Cheers,
Nguyen

**Comment by groovemen** [comment]
Hi nguyenlnc, 

Please erase the `max-height` and also set `padding: 0`  for the `navbar`.

Best, Stefan

**Comment by nguyenlnc** [comment]
Hi groovemen,

It worked. Thank you for your support. Please let me know when the new version is available for download

Cheers,
Nguyen
