### ISSUE TITLE
navbar sass errors

### ISSUE THREAD

**Issue by Gummibeer** [creativetimofficial/light-bootstrap-dashboard-pro#45]
I got errors in my `navbar.scss`:
* **resources/assets/sass/lbd/_navbars.scss:206** - *selector expected*
* **resources/assets/sass/lbd/_navbars.scss:171** - *unexpected term*

**Comment by alexandru-paduraru** [comment]
@Gummibeer thank you for using our product. What compiler do you use and what did you try to achieve? On our side, everything seems to work fine.

**Comment by Gummibeer** [comment]
I'm using Laravel Mix which uses webpack under the hood. After I reloaded all the files it now also seems ok. No idea what was going wrong. 😕
